export const PHASES = {
  IDLE: "idle",
  READING: "reading",
  FLYING: "flying",
  DONE: "done",
};

export const ANALYSE_CONFIG = {
  WORD_INTERVAL: 60,
  LINE_PAUSE: 200,
  SCROLL_DURATION: 500,

  HOVER_DURATION: 300,
  BASE_FLY_INTERVAL: 500,
  FLY_ACCEL: 0.85,
  FLY_DURATION: 600,

  MISSING_NODE_INTERVAL: 100,
  POST_MENTION_DELAY: 400,
  FADE_DURATION: 500,
  GRAPH_SWITCH_DELAY: 1000,
};
