export const PHASES = {
  IDLE: "idle",
  READING: "reading",
  FLYING: "flying",
  DONE: "done",
};

export const ANALYSE_CONFIG = {
  WORD_INTERVAL: 1,
  LINE_PAUSE: 1,
  SCROLL_DURATION: 1,

  HOVER_DURATION: 1,
  BASE_FLY_INTERVAL: 1,
  FLY_ACCEL: 0.85,
  FLY_DURATION: 1,

  MISSING_NODE_INTERVAL: 1,
  POST_MENTION_DELAY: 1,
  FADE_DURATION: 1,
  GRAPH_SWITCH_DELAY: 1,
};
